// Generated by https://github.com/juliettef/IconFontCppHeaders script GenerateIconFontCppHeaders.py
// for C and C++
// from codepoints https://github.com/FortAwesome/Font-Awesome/raw/6.x/metadata/icons.yml
// for use with font https://github.com/FortAwesome/Font-Awesome/blob/6.x/webfonts/fa-regular-400.ttf, https://github.com/FortAwesome/Font-Awesome/blob/6.x/webfonts/fa-solid-900.ttf

#pragma once

#define FONT_ICON_FILE_NAME_FAR "fa-regular-400.ttf"
#define FONT_ICON_FILE_NAME_FAS "fa-solid-900.ttf"

#define ICON_MIN_FA 0xe005
#define ICON_MAX_16_FA 0xf8ff
#define ICON_MAX_FA 0xf8ff

#define ICON_FA_EYE "\xef\x81\xae" // U+f06e
#define ICON_FA_EYE_SLASH "\xef\x81\xb0" // U+f070
#define ICON_FA_FOLDER "\xef\x81\xbb" // U+f07b
#define ICON_FA_FOLDER_OPEN "\xef\x81\xbc" // U+f07c
#define ICON_FA_MAGNIFYING_GLASS "\xef\x80\x82" // U+f002
#define ICON_FA_GEAR "\xef\x80\x93" // U+f013
#define ICON_FA_FLOPPY_DISK "\xef\x83\x87" // U+f0c7
#define ICON_FA_FILE "\xef\x85\x9b" // U+f15b
#define ICON_FA_PLUS "\xef\x83\xbe" // U+f0fe
#define ICON_FA_CUBE "\xef\x86\xb2" // U+f1b2
#define ICON_FA_PAINTBRUSH "\xef\x87\xbc" // U+f1fc
#define ICON_FA_ARROWS_UP_DOWN_LEFT_RIGHT "\xef\x81\x87" // U+f047
#define ICON_FA_ARROWS_ROTATE "\xef\x80\xa1" // U+f021
#define ICON_FA_UP_RIGHT_AND_DOWN_LEFT_FROM_CENTER "\xef\x90\xa4" // U+f424
#define ICON_FA_VIDEO "\xef\x80\xbd" // U+f03d
#define ICON_FA_CHART_LINE "\xef\x88\x81" // U+f201
#define ICON_FA_UNDO "\xef\x83\xa2" // U+f0e2 - arrow-rotate-left
#define ICON_FA_REDO "\xef\x80\x9e" // U+f01e - arrow-rotate-right
#define ICON_FA_CODE "\xef\x84\xa1" // U+f121
#define ICON_FA_FILM "\xef\x80\x88" // U+f008
#define ICON_FA_SWATCHBOOK "\xef\x97\x83" // U+f5c3
#define ICON_FA_OBJECT_GROUP "\xef\x89\x87" // U+f247
#define ICON_FA_IMAGE "\xef\x80\xbe" // U+f03e
#define ICON_FA_ANGLES_LEFT "\xef\x84\x80" // U+f100
#define ICON_FA_LIST "\xef\x80\xba" // U+f03a
#define ICON_FA_GRIP "\xef\x96\x8d" // U+f58d
#define ICON_FA_PLAY "\xef\x81\x8b" // U+f04b
#define ICON_FA_STOP "\xef\x81\x8d" // U+f04d
#define ICON_FA_HAND "\xef\x89\x96" // U+f256
#define ICON_FA_GRIP_LINES "\xef\x9e\xa4" // U+f7a4 - parallel lines
#define ICON_FA_FILTER "\xef\x82\xb0" // U+f0b0 - converging lines (perspective)
